<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class PermissionSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {        
        DB::table('permissions')->insert([
            [
                'id' => 1,
                'module' => 'user',
                'module_fa' => 'مدیریت کاربران',
                'name' => 'list',
                'name_fa' => 'نمایش لیست',
                'slug' => 'user_list',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'module' => 'user',
                'module_fa' => 'مدیریت کاربران',
                'name' => 'create',
                'name_fa' => 'اضافه کردن',
                'slug' => 'user_create',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'module' => 'user',
                'module_fa' => 'مدیریت کاربران',
                'name' => 'edit',
                'name_fa' => 'ویرایش کردن',
                'slug' => 'user_edit',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'module' => 'user',
                'module_fa' => 'مدیریت کاربران',
                'name' => 'editpassword',
                'name_fa' => 'ویرایش پسورد',
                'slug' => 'user_editpassword',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'module' => 'user',
                'module_fa' => 'مدیریت کاربران',
                'name' => 'delete',
                'name_fa' => 'حذف',
                'slug' => 'user_delete',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 6,
                'module' => 'user',
                'module_fa' => 'مدیریت کاربران',
                'name' => 'show',
                'name_fa' => 'نمایش جزییات',
                'slug' => 'user_show',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 7,
                'module' => 'user',
                'module_fa' => 'مدیریت کاربران',
                'name' => 'all',
                'name_fa' => 'همه',
                'slug' => 'user_all',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 8,
                'module' => 'role',
                'module_fa' => 'مدیریت نقش ها',
                'name' => 'list',
                'name_fa' => 'نمایش لیست',
                'slug' => 'role_list',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 9,
                'module' => 'role',
                'module_fa' => 'مدیریت نقش ها',
                'name' => 'create',
                'name_fa' => 'اضافه کردن',
                'slug' => 'role_create',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 10,
                'module' => 'role',
                'module_fa' => 'مدیریت نقش ها',
                'name' => 'edit',
                'name_fa' => 'ویرایش کردن',
                'slug' => 'role_edit',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 11,
                'module' => 'role',
                'module_fa' => 'مدیریت نقش ها',
                'name' => 'assign user',
                'name_fa' => 'اختصاص دادن به کاربر',
                'slug' => 'role_assign_user',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 12,
                'module' => 'role',
                'module_fa' => 'مدیریت نقش ها',
                'name' => 'assign permission',
                'name_fa' => 'اختصاص دادن به سطح دسترسی ها',
                'slug' => 'role_assign_permission',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 13,
                'module' => 'role',
                'module_fa' => 'مدیریت نقش ها',
                'name' => 'delete',
                'name_fa' => 'حذف',
                'slug' => 'role_delete',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 14,
                'module' => 'role',
                'module_fa' => 'مدیریت نقش ها',
                'name' => 'show',
                'name_fa' => 'نمایش جزییات',
                'slug' => 'role_show',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 15,
                'module' => 'role',
                'module_fa' => 'مدیریت نقش ها',
                'name' => 'all',
                'name_fa' => 'همه',
                'slug' => 'role_all',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 16,
                'module' => 'category',
                'module_fa' => 'مدیریت دسته بندی ها',
                'name' => 'list',
                'name_fa' => 'نمایش لیست',
                'slug' => 'category_list',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 17,
                'module' => 'category',
                'module_fa' => 'مدیریت دسته بندی ها',
                'name' => 'create',
                'name_fa' => 'اضافه کردن',
                'slug' => 'category_create',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 18,
                'module' => 'category',
                'module_fa' => 'مدیریت دسته بندی ها',
                'name' => 'edit',
                'name_fa' => 'ویرایش کردن',
                'slug' => 'category_edit',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 19,
                'module' => 'category',
                'module_fa' => 'مدیریت دسته بندی ها',
                'name' => 'delete',
                'name_fa' => 'حذف',
                'slug' => 'category_delete',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 20,
                'module' => 'category',
                'module_fa' => 'مدیریت دسته بندی ها',
                'name' => 'show',
                'name_fa' => 'نمایش جزییات',
                'slug' => 'category_show',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 21,
                'module' => 'category',
                'module_fa' => 'مدیریت دسته بندی ها',
                'name' => 'all',
                'name_fa' => 'همه',
                'slug' => 'category_all',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 28,
                'module' => 'product',
                'module_fa' => 'مدیریت محصولات',
                'name' => 'list',
                'name_fa' => 'نمایش لیست',
                'slug' => 'product_list',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 29,
                'module' => 'product',
                'module_fa' => 'مدیریت محصولات',
                'name' => 'create',
                'name_fa' => 'اضافه کردن',
                'slug' => 'product_create',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 30,
                'module' => 'product',
                'module_fa' => 'مدیریت محصولات',
                'name' => 'edit',
                'name_fa' => 'ویرایش کردن',
                'slug' => 'product_edit',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 31,
                'module' => 'product',
                'module_fa' => 'مدیریت محصولات',
                'name' => 'delete',
                'name_fa' => 'حذف',
                'slug' => 'product_delete',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 32,
                'module' => 'product',
                'module_fa' => 'مدیریت محصولات',
                'name' => 'show',
                'name_fa' => 'نمایش جزییات',
                'slug' => 'product_show',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 33,
                'module' => 'product',
                'module_fa' => 'مدیریت محصولات',
                'name' => 'all',
                'name_fa' => 'همه',
                'slug' => 'product_all',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 34,
                'module' => 'customer',
                'module_fa' => 'مدیریت مشتریان',
                'name' => 'list',
                'name_fa' => 'نمایش لیست',
                'slug' => 'customer_list',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 35,
                'module' => 'customer',
                'module_fa' => 'مدیریت مشتریان',
                'name' => 'create',
                'name_fa' => 'اضافه کردن',
                'slug' => 'customer_create',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 36,
                'module' => 'customer',
                'module_fa' => 'مدیریت مشتریان',
                'name' => 'edit',
                'name_fa' => 'ویرایش کردن',
                'slug' => 'customer_edit',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 37,
                'module' => 'customer',
                'module_fa' => 'مدیریت مشتریان',
                'name' => 'delete',
                'name_fa' => 'حذف',
                'slug' => 'customer_delete',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 38,
                'module' => 'customer',
                'module_fa' => 'مدیریت مشتریان',
                'name' => 'show',
                'name_fa' => 'نمایش جزییات',
                'slug' => 'customer_show',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 39,
                'module' => 'customer',
                'module_fa' => 'مدیریت مشتریان',
                'name' => 'all',
                'name_fa' => 'همه',
                'slug' => 'customer_all',
                'created_user_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
        ]);
    }
}
